CAPTURE_FPS = 20
DAMAGE_ROI = None

MIN_DAMAGE_VALUE = 1
MAX_DAMAGE_VALUE = 99_999_999
MIN_DETECTION_CONFIDENCE = 0.5

TRACK_TTL = 0.4
STABLE_FRAME_COUNT = 2
POSITION_MATCH_DISTANCE = 48
OVERLAP_IOU_THRESHOLD = 0.65

MOCK_OCR = True
MOCK_OCR_INTERVAL_SECONDS = 1.0
